telegram_token = 'xxx'
Api_Auth_Token = 'xxxx'
Sms_ru_api_Token = 'xxx'
table_name = 'xxxx'
database_name = 'xxx.db'
webhook_ip = 'xxx'
webhook_ssl_certificate = 'xxx'# Путь к сертификату
webhook_ssl_private = 'xxx' # Путь к приватному ключу
side_numbers_forwarding = True
